man-group/pytest-plugins

pytest-profiling/README.md, pytest-profiling/pytest_profiling.py, pytest-profiling/tests/unit/test_profile.py
Sometimes test names (especially when using `pytest.mark.parametrize`) may be so long that profile file path exceeds maximum length.
This PR solves that problem by replacing test name by its hash.
=> fix: avoid errors when filename is too long

pytest-profiling/pytest_profiling.py
Windows notoriously chokes on certain characters in filenames, so take
those out to avoid failing tests.
=> Clean suspect characters out of .prof filenames

circle.yml, pytest-fixture-config/pytest_fixture_config.py, pytest-server-fixtures/pytest_server_fixtures/rethink.py, pytest-shutil/pytest_shutil/run.py, pytest-shutil/pytest_shutil/workspace.py, pytest-shutil/tests/unit/test_run.py
I fixed running tests on Python 3 for `pytest-fixture-config`, `pytest-shutil` and `pytest-virtualenv`.
Other libraries tests fails, so I didn't enabled them currently for Python 3.
This PR includes fix from #14 and partly fixes #15.
=> Add CircleCI configuration to run tests on Python 3 + fix several Python 3 issues

pytest-shutil/pytest_shutil/cmdline.py
This commit updates the function so that it works appropriately when
running test (using any plugin making use of cmdline) from within a virtual
env based of python 3.x using:
```
python setup.py test
```
where both
```
/path/to/.virtualenvs/my-env/bin/python
/path/to/.virtualenvs/my-env/bin/python3
```
are symbolic to
```
/path/to/.virtualenvs/my-env/bin/python3.x
```
with
```
/path/to/.virtualenvs/my-env/bin/python3.x
```
being itself a copy of
```
/usr/bin/python3.x
```
Without this change, the value returned by
```
cmdline.get_real_python_executable()
```
was
```
/usr/bin/python
```
whereas
```
/usr/bin/python3.x
```
was expected.
=> shutil/cmdline: Update get_real_python_executable to resolve symbolic link

pytest-virtualenv/pytest_virtualenv.py
Invoking "installed_packages" on windows fails because it is trying to
execute multi-line python code as a string with "shell=true". In that
case, "cmd.exe" fails because it does NOT know how to handle newline
character.  This confirmed by example (2) reported below.
Instead, this commit passes the command as an array of arguments that
ends up calling subprocess.Popen with "shell=false".
Examples:
1) Executing "import sys; print(sys.path)": OK
```
C:\Users\appveyor>cmd.exe /c python -c "import sys; print(sys.path)"
['', 'C:\\windows\\SYSTEM32\\python27.zip', 'C:\\Python27\\DLLs', 'C:\\Python27\
\lib', 'C:\\Python27\\lib\\plat-win', 'C:\\Python27\\lib\\lib-tk', 'C:\\Python27
', 'C:\\Python27\\lib\\site-packages']
```
2) Executing "import sys\nfor p in sys.path: print(p)": FAIL
``` …
```
=> virtualenv/installed_packages: Add support for windows

pytest-server-fixtures/pytest_server_fixtures/base.py, pytest-server-fixtures/pytest_server_fixtures/rethink.py
Change the behavior of the test server in the server fixtures to behave in one of two ways:
if a hostname is not specified, use a random ip/port to connect to the instance. 
if a hostname is specified, that will be used to connect. 
Hostname is config is no longer used.
=> Fix issue 42

pytest-server-fixtures/pytest_server_fixtures/base.py
This hangs indefinitely on macOS for an unknown reason.
I confirmed that this fix works for me on my machine
=> Fix #44 - don't try to bind a random port.

pytest-profiling/pytest_profiling.py
The `gprof2dot` executable was not found when it's not in the same directory as the python executable. By inverting the logic in `Profiling.__init__`, the executable is searched on $PATH, as was the intention.
=> Fix gprof2dot not found error

pytest-server-fixtures/pytest_server_fixtures/http.py
python 3 compatibility: `SimpleHTTPServer` became `http.server`
see http://python-future.org/compatible_idioms.html
currently on py3 it fails with:
```
bin/python: No module named SimpleHTTPServer
```
=> python 3 compatibility: SimpleHTTPServer became http.server

CHANGES.md, pytest-devpi-server/setup.py, pytest-fixture-config/setup.py, pytest-git/setup.py, pytest-listener/setup.py, pytest-profiling/setup.py, pytest-pyramid-server/setup.py, pytest-qt-app/setup.py, pytest-server-fixtures/setup.py, pytest-shutil/setup.py, pytest-svn/setup.py, pytest-verbose-parametrize/setup.py, pytest-virtualenv/setup.py, pytest-webdriver/setup.py
Pytest just released 4.0.0, which treats all RemovedInPytest4Warnings as errors. In the long run we probably need to fix the tests to remove all warnings instead. But we need the tests to pass for now... So pinning pytest==3.10.1
=> Pin pytest to 3.10.1

CHANGES.md, pytest-fixture-config/README.md, pytest-fixture-config/pytest_fixture_config.py, pytest-fixture-config/tests/unit/test_fixture_config.py, pytest-server-fixtures/pytest_server_fixtures/httpd.py, pytest-server-fixtures/pytest_server_fixtures/jenkins.py, pytest-server-fixtures/pytest_server_fixtures/mongo.py, pytest-server-fixtures/pytest_server_fixtures/redis.py, pytest-server-fixtures/pytest_server_fixtures/rethink.py, pytest-server-fixtures/pytest_server_fixtures/s3.py, pytest-server-fixtures/pytest_server_fixtures/xvfb.py, pytest-virtualenv/pytest_virtualenv.py
Fix docs and tests due to pytest 3.7.1
pytest 3.7.1 changed behavior for fixture decorators. But later in 3.7.2 this was fixed by adding of ```__pytest_wrapped__``` attribute, which is used to obtain the function up until the point a function was wrapped by pytest itself.
For related info please look at https://github.com/pytest-dev/pytest/pull/3780
Removing of functionality is a surprise for most users/developers.
Meanwhile, fixture_config is used by setuptools for testing.
=> Fix fixture config

pytest-git/README.md, pytest-shutil/README.md, pytest-svn/README.md, pytest-virtualenv/README.md
The previous link gives error 404
=> Fix broken link to path.py documentation

CHANGES.md, pytest-server-fixtures/pytest_server_fixtures/base2.py
The function which exists in TestServer, was missing from TestServerV2. Add it to keep better backward compatibility.
=> Add kill() to TestServerV2

CHANGES.md, pytest-server-fixtures/pytest_server_fixtures/base2.py
this prevents the following error:
"Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads"
=> pytest-server-fixtures: suppress stacktrace if kill() is called

CHANGES.md, pytest-server-fixtures/pytest_server_fixtures/__init__.py
Locally I constantly get #127 because I dont have a host defined on my laptop. This is a reasonable workaround (in my opinion).
=> Error if hostname not defined

pytest-listener/pytest_listener.py, pytest-profiling/pytest_profiling.py, pytest-webdriver/pytest_webdriver.py
After calling pytest.main twice, pytest creates this `warning summary `
```bash
===================================================================== warnings summary =====================================================================
~/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:272
~/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:272: PytestWarning: Module already imported so cannot be rewritten: pytest_profiling
self.config,
...
```
According to 
* https://github.com/pytest-dev/pytest/issues/2995
* https://github.com/pytest-dev/pytest-cov/pull/228/commits/22387a604ce8a082cc6381f1bbc28fa434c97bbe
the doc string `PYTEST_DONT_REWRITE` can be used to suppress this warning.
=> add PYTEST_DONT_REWRITE in order to suppress module already imported

Makefile, pytest-devpi-server/README.md, pytest-fixture-config/README.md, pytest-git/README.md, pytest-listener/README.md, pytest-profiling/README.md, pytest-pyramid-server/README.md, pytest-qt-app/README.md, pytest-shutil/README.md, pytest-svn/README.md, pytest-verbose-parametrize/README.md, pytest-virtualenv/README.md, pytest-webdriver/README.md
This reverts commit dd239fd9aa4ed1c1dfb7f21d2b8952b9ac4ebb90.
=> Revert "dist: Remove support for building and distributing *.egg files"

pytest-devpi-server/setup.py
Since no python 3.4 wheels are distributed following ruamel.yaml 0.15.94,
this commit updates the requirements to ensure the package still be installed
using python 3.4
It addresses the following error:
```
Searching for ruamel.yaml>=0.14.2
Reading https://pypi.org/simple/ruamel.yaml/
Downloading https://files.pythonhosted.org/packages/a2/f7/63f04dd8a572b13a41a62b29eb52b64a2136249cc42a933f05d890033eac/ruamel.yaml-0.15.96.tar.gz#sha256=343ace5ffbab036536a3da65e4cfd31b8292388a389f6305744984581a479b2a
Best match: ruamel.yaml 0.15.96
Processing ruamel.yaml-0.15.96.tar.gz
Writing /tmp/easy_install-gpfme0if/ruamel.yaml-0.15.96/setup.cfg
Running ruamel.yaml-0.15.96/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gpfme0if/ruamel.yaml-0.15.96/egg-dist-tmp-ncvinjfp
minimum python version(s): …
```
=> Fix pytest-devpi-server test on py34 updating "ruamel.yaml" requirements

README.md
Joking aside, the official name for pytest should be `pytest`, all lower cases, no dots.
Thanks for the project! 😁
=> #dropthedot

pytest-profiling/README.md
Moved from Google Code to GitHub.
=> pytest-profiling README correct link to gprof2dot

pytest-profiling/pytest_profiling.py, pytest-verbose-parametrize/pytest_verbose_parametrize.py
=> Fix deprecation warnings

pytest-git/README.md, pytest-pyramid-server/README.md, pytest-server-fixtures/README.md, pytest-shutil/README.md, pytest-shutil/setup.py, pytest-svn/README.md
Unless there's some obscure backwards-compatibility reason, I think you should import path instead of path.py.
This actually leads to a problem downstream on conda-forge: since the conda-forge path.py package is just a wrapper for path, no package named path.py is installed, leaving pip in an inconsistent state due to this package's explicit dependence on path.py.
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=286865&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=210
=> Replace path.py with path

pytest-server-fixtures/pytest_server_fixtures/postgres.py
Psycopg 2.9 uses transaction blocks withing context managers,
which is not allowed for `CREATE DATABASE`
https://github.com/psycopg/psycopg2/issues/941
=> pytest-server-fixtures: Don't use context manager for CREATE DATABASE

pytest-devpi-server/_pytest_devpi_server/__init__.py, pytest-devpi-server/tests/integration/test_devpi_server.py
Fixture now initializes properly.
See https://pypi.org/project/devpi-server/5.2.0/ for information on why these changes (or similar) are necessary.
Addresses #179
=> devpi now requires devpi-init for initialization.

Makefile, pytest-server-fixtures/pytest_server_fixtures/rethink.py, pytest-server-fixtures/setup.py
This PR makes the pytest rethink plugin compatible with latest rethinkdb-python client
=> pytest rethink update

pytest-profiling/pytest_profiling.py
Fixes: https://github.com/man-group/pytest-plugins/issues/95
=> Add: support to hide/show the full path of file

pytest-server-fixtures/pytest_server_fixtures/mongo.py
When checking the Mongo server has come up properly, the `MongoTestServer`
class first creates a `pymongo.MongoClient` with a short timeout to avoid
waiting a long time in the failure case. After this it creates another
client with the default timeouts, but prior to this change, the initial
client is not closed.
This change explicitly closes the initial client after use.
=> pytest-server-fixtures: Explicitly close initial Mongo client

pytest-server-fixtures/README.md
The example incorrectly uses `bucket_name` instead of `name` to get the bucket UUID.
=> Fixed S3 bucket doc

pytest-server-fixtures/pytest_server_fixtures/base.py
Thanks for the nice project. 
I am getting deprecation warnings running the `s3_bucket` fixture; here's a small PR to fix that. 
The new way to do this is to `daemon = True`
=> setDaemon is deprecated

common_setup.py, pytest-virtualenv/setup.py
Currently, installation of `pytest-virtualenv` plugin fails due to outdated usage of setuptools.
<details>
<summary> Error trace </summary>
```
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [46 lines of output]
/tmp/pip-install-4nhyz4jn/pytest-virtualenv_93370f578ce6437fa8e558311740de5f/common_setup.py:6: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
!!
********************************************************************************
Please remove any references to `setuptools.command.test` in all supported versions of the affected package.
By 2024-Nov-15, you need to update your project and remove deprecated calls
or your builds will no longer be supported. …
```
=> Fix: use extras_requires instead of tests_requires to install pytest-virtualenv

pytest-virtualenv/setup.py
Removed since it is for unsupported python versions. This was causing the master build to fail.
=> [pytest-virtualenv] Remove extras_require

pytest-shutil/pytest_shutil/run.py
Replace the use of the deprecated `imp` module with `importlib.util', as the former has been removed from Python 3.12.
=> pytest-shutil: Replace deprecated imp module

pytest-verbose-parametrize/pytest_verbose_parametrize.py
removing old import that's not needed since py 3.3
=> fixing import for py 3.11 compatibility

pytest-profiling/tests/unit/test_profile.py
In Python < 3.12, MagicMock's will blindly call any method provided to them, which is masking a real issue in this testcase. The correct method is assert_called_with(), and even worse, one of the arguments provided isn't correct either. Correct the method call, and provide the correct argument.
=> pytest-profiling: Fix mock in test_writes_summary

pytest-shutil/pytest_shutil/cmdline.py, pytest-shutil/tests/unit/test_cmdline.py
Since termcolor 2.1.0, the library will now detect whether or not the process is running a TTY and disable outputting color if so. This broke using the `--color` argument to force color when piping to another process (e.g. `less`), as well as our pytest function for checking rendered output.
The fix is ensuring that we set the environment variable FORCE_COLOR in the cases where we want color, and might not have a TTY (e.g. in the pytest, or when using `--color` option).
Fixes #210
=> Fix forcing color through termcolor

pytest-devpi-server/_pytest_devpi_server/__init__.py, pytest-devpi-server/setup.py, pytest-devpi-server/tests/integration/test_devpi_server.py, pytest-profiling/tests/integration/test_profile_integration.py, pytest-pyramid-server/pytest_pyramid_server.py, pytest-server-fixtures/pytest_server_fixtures/httpd.py, pytest-server-fixtures/setup.py, pytest-server-fixtures/tests/integration/test_httpd_proxy_server.py, pytest-shutil/pytest_shutil/run.py, pytest-shutil/pytest_shutil/workspace.py, pytest-shutil/setup.py, pytest-shutil/tests/unit/test_cmdline.py, pytest-virtualenv/pytest_virtualenv.py
**What**
Replace Path/path.py usages with pathlib.Path across the entire repo. Also removing references to outdated python versions and unused imports. 
**Why**
To address #224 which is currently breaking a number of other builds since the renaming of Path::isdir() to Path::is_dir(). We don't really need the dependency since we can use functions from the standard library.
=> #224: Fix the use of Path, which renamed isdir() to is_dir().

pytest-server-fixtures/pytest_server_fixtures/httpd.py
Now that the config file we create is a pathlib.Path object, we must convert it to a string before we try and use it, so do so.
=> pytest-server-fixtures: Correct httpd command line

pytest-listener/setup.py
This package does not use a package directory, so when building a wheel, no code is included. Use the correct keyword, py_modules.
=> pytest-listener: Use py_modules in setup.py
